feat(wallet): support clearing chain data and resyncing
witnet/witnet-rust pull request #1675
Opened 2020-10-22 17:14 UTC by aesedepece

2020-10-22 17:17 UTC, aesedepece commented on wallet/src/repository/wallet/mod.rs
> +    }
This is were theoretically we could actually delete data from the storage.

2020-10-23 08:37 UTC, mariocao requested changes

2020-10-23 08:37 UTC, mariocao commented on wallet/src/db/encrypted/mod.rs
> +
This key is not correct! :) Maybe we should take this delete feature from this PR as it is not used.

2020-10-23 08:55 UTC, mariocao commented
As you mentioned to me, re-syncing several times may lead to some problems.
We should about this by avoiding re-syncing while syncing using this condition:
```
        // Exit if not syncing
        if state.transient_internal_addresses.is_empty()
            && state.transient_external_addresses.is_empty()
```

2020-10-23 13:31 UTC, tmpolaczyk commented on wallet/src/repository/wallet/mod.rs
> +            && state.transient_external_addresses.is_empty()
I would prefer using a dedicated "syncing" flag instead of reusing other fields.

2020-10-23 14:39 UTC, girazoki commented on wallet/src/actors/worker/methods.rs
> +        // Only trigger sync of chain data has been cleared
```suggestion
        // Only trigger sync of chain after data has been cleared
```

2020-10-23 14:39 UTC, girazoki commented on wallet/src/repository/wallet/mod.rs
> +        if state.is_syncing() {
If I understand correctly, if is_syncing is true we clear data and issue a re-sync. I would change the naming as this is a bit confusing to me

2020-10-23 15:55 UTC, girazoki approved these changes

2020-10-23 16:15 UTC, merged