feat: implement signalingInfo JSON-RPC method
witnet/witnet-rust pull request #1937
Opened 2021-05-19 11:29 UTC by tmpolaczyk

2021-05-19 15:10 UTC, lrubiorod commented
and CLI method?

2021-05-19 15:47 UTC, tmpolaczyk commented
> and CLI method?

In another issue

2021-05-19 15:56 UTC, lrubiorod commented
> > and CLI method?
> 
> In another issue

😢

2021-05-21 07:48 UTC, aesedepece requested changes

2021-05-21 07:48 UTC, aesedepece commented on node/src/actors/messages.rs
> +    pub voting: Vec<BitVotesCounter>,
```suggestion
    /// List of protocol upgrades that are already active, and their activation epoch
    pub active_upgrades: HashMap<String, Epoch>,
    /// List of protocol upgrades that are currently being polled for activation signaling
    pub pending_upgrades: Vec<BitVotesCounter>,
```

2021-05-21 10:16 UTC, aesedepece approved these changes

2021-05-21 11:01 UTC, merged