doc(tapi): include TODO to rename version by signals
witnet/witnet-rust pull request #1939
Opened 2021-05-21 10:28 UTC by lrubiorod

2021-05-21 10:30 UTC, aesedepece commented on data_structures/src/chain.rs
> +    // TODO: Rename `version` to `signals` when we support migrations
Why? AFAIK fields can be safely renamed.

2021-05-21 10:31 UTC, tmpolaczyk commented on data_structures/src/chain.rs
>      pub version: u32,
Renaming is supported by both bincode and protobuf, but it would break the JSON-RPC API.

2021-05-24 14:53 UTC, tmpolaczyk commented
So this definitely breaks the JSON-RPC API, but in an expected way. We assume that nobody was using the old `version` field, and any client that wants to add a signaling monitor will need to update in order to support it.

However, this will break any client that uses the `getBlock` method, for example the wallet. This is because the version field is needed to deserialize the JSON object as a witnet `Block`. This wouldn't be a problem if the `getBlock` method used protobuf as the serialization format. Possible solutions:

1. Do nothing, close this PR
2. Use `serde(rename = "version")` to keep compatibility in the JSON-RPC API
3. Add an extra version field after the serialization, similar to how we add the "blockHashes" field.
4. Break the API. This means updating all the nodes and all the clients that may be affected. We may want to use this opportunity to change other aspects of the JSON-RPC API.

I prefer 1) because it's the one with less unexpected side effects.

2021-06-10 14:40 UTC, mariocao commented
Option 4 is mentioned in the [WIP-0014](https://github.com/witnet/WIPs/blob/master/wip-0014.md) as the improvement labeled as **(1)**.

2021-06-10 14:41 UTC, mariocao reviewed
Option 4 is mentioned in the [WIP-0014](https://github.com/witnet/WIPs/blob/master/wip-0014.md) as the improvement labeled as (1).

2021-06-14 12:56 UTC, aesedepece approved these changes

2021-06-14 12:57 UTC, aesedepece requested changes

2021-06-14 12:57 UTC, aesedepece commented on data_structures/src/chain.rs
> +    /// 32 bits for binary signaling new witnet protocol improvements
Let's link to WIP-0014 here

2021-06-16 08:10 UTC, mariocao commented on data_structures/src/chain.rs
> +    /// 32 bits for binary signaling new witnet protocol improvements
That would be great

2021-06-16 13:26 UTC, aesedepece requested changes

2021-06-16 13:26 UTC, aesedepece commented on data_structures/src/chain.rs
> +    /// https://github.com/witnet/WIPs/blob/master/wip-0014.md
```suggestion
    /// 32 bits for binary signaling new witnet protocol improvements.
    /// See [WIP-0014](https://github.com/witnet/WIPs/blob/master/wip-0014.md) for more info.
```

2021-07-05 12:49 UTC, tmpolaczyk commented on validations/src/tests.rs
>          // Flip one bit of the version field
```suggestion
        // Flip one bit of the signals field
```

2021-07-05 12:50 UTC, tmpolaczyk commented on validations/src/tests.rs
>          // If the miner changes the version field and then signs the block, the block will be valid
```suggestion
        // If the miner changes the signals field and then signs the block, the block will be valid
```

2021-07-05 12:50 UTC, tmpolaczyk commented on validations/src/tests.rs
>          // Flip one bit of the version field
And also the test name

2021-07-05 13:37 UTC, tmpolaczyk approved these changes

2021-07-06 11:47 UTC, aesedepece approved these changes

2021-07-06 12:47 UTC, merged