refactor: clarify data request transaction weight formula
witnet/witnet-rust pull request #1966
Opened 2021-06-10 14:43 UTC by tmpolaczyk

2021-06-10 14:45 UTC, mariocao commented on data_structures/src/transaction.rs
> +        // DR_weight = DR_output_size + W*COMMIT + W*REVEAL*beta + TALLY*beta + (W + M)*OUTPUT_SIZE + N*INPUT_SIZE
```suggestion
        // DR_weight = DR_output_size*alpha + W*COMMIT + W*REVEAL*beta + TALLY*beta + (W + M)*OUTPUT_SIZE + N*INPUT_SIZE
```

2021-06-10 14:48 UTC, lrubiorod commented on data_structures/src/transaction.rs
> +        let dr_weight = self.dr_output.weight().saturating_mul(ALPHA);
```suggestion
        let dr_output_size = self.dr_output.weight().saturating_mul(ALPHA);
```

2021-06-11 09:33 UTC, mariocao approved these changes

2021-06-11 14:43 UTC, lrubiorod approved these changes

2021-06-14 12:22 UTC, aesedepece requested changes

2021-06-14 12:22 UTC, aesedepece commented on data_structures/src/transaction.rs
> +        // DR_weight = DR_output_size*alpha + W*COMMIT + W*REVEAL*beta + TALLY*beta + N*INPUT_SIZE + (W + M)*OUTPUT_SIZE
What about moving the formula to the documentation of the function?

2021-06-18 08:32 UTC, aesedepece approved these changes

2021-06-18 08:48 UTC, merged