Delete wallet
witnet/witnet-rust pull request #2023
Opened 2021-07-22 16:00 UTC by lrubiorod

2021-07-27 14:51 UTC, tmpolaczyk approved these changes

2021-07-28 15:36 UTC, mariocao commented on wallet/src/actors/app/methods.rs
> +    /// Delete wallet
I think you can document this better :rofl:

2021-07-28 15:38 UTC, mariocao commented on wallet/src/actors/worker/methods.rs
> +    /// Delete wallet
Same here

2021-07-28 15:41 UTC, mariocao commented on wallet/src/repository/wallets/mod.rs
> +    /// Delete a wallet by its id
```suggestion
    /// Delete a wallet by its ID
```

2021-07-28 15:47 UTC, mariocao commented on wallet/src/repository/wallets/mod.rs
> +        // FIXME: Use merge operator or a transaction when available in rocksdb crate
```suggestion
```

2021-07-29 08:19 UTC, mariocao requested changes
I just discovered that `delete_wallet` does not remove the wallet session. Therefore, other API calls are still allowed (e.g. `generate_address`) which does not make much sense. :smile:

2021-07-29 09:48 UTC, mariocao reviewed
I discovered another "strange" flow:

1. Create wallet
2. Unlock wallet -> session id
3. Delete wallet
4. Unlock wallet with `session_id` --> IT WORKS! :)

`unlock_wallet` does not check if the `wallet_id` exists in the list of known wallets.
It directly tries to decrypt the wallet from the database.

It is not an error per se, but it could feel strange for a user.

2021-07-29 13:44 UTC, tmpolaczyk commented on wallet/src/repository/wallets/mod.rs
> +        if !ids.contains(&id.to_string()) {
Add a comment, mention that this is needed because deleted otherwise wallets can still be unlocked.

2021-07-29 14:13 UTC, mariocao approved these changes

2021-07-29 14:29 UTC, tmpolaczyk approved these changes

2021-07-29 14:34 UTC, merged