feat(stack): implement control flow and checktimelock
witnet/witnet-rust pull request #2217
Opened 2022-06-07 14:54 UTC by tmpolaczyk

2022-06-08 08:53 UTC, aesedepece requested changes

2022-06-08 08:53 UTC, aesedepece commented on stack/src/lib.rs
> +                if_stack.push_back(bool);
Lol you shadowed the reserved `bool` word here.

2022-06-08 16:24 UTC, aesedepece commented
This is looking great. Let's address the TODOs and go for it.

2022-06-09 09:15 UTC, lrubiorod commented on node/src/actors/chain_manager/handlers.rs
>                      .into_actor(self)
If you are not going to use the signature, you can remove the call:

```rust
            Ok(vtt) => {
                let multi_sig_witness = witnet_stack::encode(vec![]).unwrap();
                let num_inputs = vtt.inputs.len();
                let transaction = Transaction::ValueTransfer(VTTransaction {
                    body: vtt,
                    witness: vec![multi_sig_witness; num_inputs],
                });

                Box::pin(actix::fut::result(Ok(transaction)))
            }
```

2022-06-16 12:34 UTC, aesedepece commented on stack/src/lib.rs
> +    }
Should we check that 2 cannot spend after timelock even if the right secret is provided? :thinking:

2022-06-20 10:46 UTC, aesedepece commented on stack/src/lib.rs
> +    }
I think that, ideally, they shouldn't. It is a sort of assumption for an atomic swap that only 1 party can spend at a time.

2022-06-20 13:46 UTC, aesedepece requested changes

2022-06-20 13:48 UTC, tmpolaczyk commented
Now the tests are failing because of a `stack.pop()` on an empty stack, this is fixed by https://github.com/aesedepece/scriptful/pull/6

2022-07-29 15:51 UTC, tmpolaczyk commented
Closing, will continue in #2240.

2022-07-29 15:51 UTC, closed without merging