ci: 🆕 add bridge building
witnet/witnet-rust pull request #2260
Opened 2022-08-30 17:34 UTC by aeweda

2022-09-01 10:00 UTC, aesedepece requested changes

2022-09-01 15:27 UTC, aeweda commented on .github/workflows/bridge.yml
> +          cargo build -p witnet-centralized-ethereum-bridge --release
can't change it, each `run:` is a separate shell, so me doing cd in the previous run has nothing to do with that one 😅

2022-09-01 15:32 UTC, aesedepece commented on .github/workflows/bridge.yml
> +          cargo build -p witnet-centralized-ethereum-bridge --release
Gotcha!

2022-09-01 15:33 UTC, aesedepece approved these changes

2022-09-02 13:50 UTC, aesedepece commented
```console
git fetch upstream
git rebase upstream/master
git push -f origin ci-add-build-for-bridge
git push upstream ci-add-build-for-bridge:master

2022-09-02 13:53 UTC, merged