feat(wallet): add pending_tx_timeout_seconds config variable
witnet/witnet-rust pull request #2268
Opened 2022-09-07 08:51 UTC by tmpolaczyk

Close #2265 

Untested

2022-09-07 10:24 UTC, tmpolaczyk commented
Setting this variable to 10 seconds in witnet.toml

```
[wallet]
pending_tx_timeout_seconds = 10
```

to try to force some double spends, and this is the result:

![Captura de pantalla de 2022-09-07 11-49-58](https://user-images.githubusercontent.com/44604217/188853207-8c979f17-9165-4686-948f-ee02477057e8.png)

The invalid transactions seem to stay in "Sending" state forever, and exiting from the wallet in sheikah makes the "Sending" transactions disappear. Triggering a "Resync" also makes those transactions disappear, but that's expected because a resync deletes all the local data. Creating more transactions or changing the transaction page does not make the "Sending" transactions disappear, that's also expected.

But the main use case of this feature is to increase the timeout, and in that case it works as expected, you cannot create invalid transactions while another transaction is still pending.

![Captura de pantalla de 2022-09-07 12-16-58](https://user-images.githubusercontent.com/44604217/188854604-c6bcdf89-ce34-4c98-8052-43af855592d9.png)

Note that this is already the default behavior, so this pull request only changes the fact that this timeout can be increased or reduced.

2022-09-07 14:01 UTC, Tommytrg approved these changes

2022-09-12 14:02 UTC, aesedepece requested changes

2022-09-12 14:02 UTC, aesedepece commented on config/src/config.rs
> +    pub pending_tx_timeout_seconds: u64,
```suggestion
    pub pending_transactions_timeout_seconds: u64,
```

2022-09-13 10:24 UTC, aesedepece approved these changes

2022-09-13 10:40 UTC, merged