feat: introduce new EncodeReveal error
witnet/witnet-rust pull request #2319
Opened 2022-11-29 13:49 UTC by tmpolaczyk

As a fix for #2312

2023-01-10 14:47 UTC, aesedepece commented
This change sounds like a good candidate for being shipped with 1.6 — behind a TAPI flag if necessary. What do you think?

2023-01-10 15:21 UTC, tmpolaczyk commented
Sure, this needs TAPI, and a WIP to add the new radon error.

2023-01-10 16:09 UTC, tmpolaczyk commented
I can write this one.

2023-01-17 15:20 UTC, tmpolaczyk commented on rad/src/types/mod.rs
> +                        if active_wips.wip0026() {
This is backwards, we want to decode a MalformedReveal before WIP activation, not after.

```suggestion
                        if !active_wips.wip0026() {
```

2023-01-24 14:41 UTC, aesedepece commented on validations/src/tests/mod.rs
> +
Thanks for this test.

2023-01-24 14:41 UTC, aesedepece requested changes

2023-01-24 14:41 UTC, aesedepece commented on validations/src/tests/mod.rs
> +    //dr_pool_with_dr_in_tally_stage_only_errors(dr_output, 1, reveal_values);
Redundant?

2023-01-24 15:04 UTC, tmpolaczyk commented on validations/src/tests/mod.rs
> +    //dr_pool_with_dr_in_tally_stage_only_errors(dr_output, 1, reveal_values);
Yes

2023-02-02 13:17 UTC, aesedepece approved these changes
This seems correct to me, and completely in line with the [WIP-0026](https://github.com/witnet/WIPs/blob/master/wip-0026.md) specification.

2023-02-02 14:42 UTC, aesedepece approved these changes

2023-02-02 14:51 UTC, merged