feat(cli): make all stake arguments required and explicitly check validator correctness
witnet/witnet-rust pull request #2462
Opened 2024-05-08 14:45 UTC by drcpu-github

2024-05-08 16:56 UTC, aesedepece requested changes

2024-05-08 16:56 UTC, aesedepece commented on node/src/actors/json_rpc/api.rs
> +        "[STAKE] A withdrawer address was provided: {}",
```suggestion
        "[STAKE] Creating stake transaction with withdrawer address: {}",
```

2024-05-08 16:56 UTC, aesedepece commented on node/src/actors/messages.rs
> +    pub authorization: String,
```suggestion
    pub authorization: MagicEither<String, KeyedSignature>,
```

2024-05-08 16:56 UTC, aesedepece commented on node/src/actors/messages.rs
> +    pub withdrawer: String,
```suggestion
    pub withdrawer: MagicEither<String, PublicKeyHash>,
```

2024-05-08 16:56 UTC, aesedepece commented on src/cli/node/json_rpc_client.rs
> +    authorization: String,
```suggestion
    authorization: MagicEither<String, KeyedSignature>,
```

2024-05-08 16:56 UTC, aesedepece commented on src/cli/node/json_rpc_client.rs
> +    validator: String,
```suggestion
    validator: MagicEither<String, PublicKeyHash>,
```

2024-05-08 16:56 UTC, aesedepece commented on src/cli/node/json_rpc_client.rs
> +    withdrawer: String,
```suggestion
    withdrawer: MagicEither<String, PublicKeyHash>,
```

2024-05-08 16:56 UTC, aesedepece commented on src/cli/node/with_node.rs
> +            withdrawer,
```suggestion
            authorization.map(MagicEither::Left),
            validator.map(MagicEither::Left),
            withdrawer.map(MagicEither::Left),
```

2024-05-14 21:18 UTC, drcpu-github commented
@aesedepece Not quite sure the `Default` implementation I had to create for `MagicEither` makes a lot of sense, so a renewed review would be appreciated.

2024-05-16 14:07 UTC, aesedepece approved these changes

2024-05-16 14:08 UTC, aesedepece commented
> @aesedepece Not quite sure the `Default` implementation I had to create for `MagicEither` makes a lot of sense, so a renewed review would be appreciated.

It's a lesser evil :sweat_smile:

2024-05-16 14:18 UTC, merged